### ISSUE TITLE
Source code?

### ISSUE THREAD

**Issue by whitetigle** [fable-compiler/samples-browser#10]
Hi!
Simple question here. 
I think it would be great to show pixi.js F# code vs JS code, side by side on every sample
Are you ok with this idea? If that's the case, I'm going to see how the samples work.
Thanks.

**Comment by MangelMaxime** [comment]
Could be something to explore if you think it's add value to the samples.

If you want to give it a try, you will need to edit [this repo](https://github.com/fable-compiler/fable-compiler.github.io) and update [this function](https://github.com/fable-compiler/fable-compiler.github.io/blob/dev/src/Main.fs#L70-L79). But we need a way to detect, if the samples is only a showcase or a showcase with source code comparison.

In the fable-compiler.github.io repo, you have access to Fulma even if we don't use it heavily inside of it yet.

**Comment by alfonsogarciacaro** [comment]
Yeah, some of the samples also have a README with commented code, I need to show that as it was done in the original site. Actually, my intention was to do it like the fable-elmish site and show the sample running in a frame with the instructions below.

**Comment by whitetigle** [comment]
ah ok. 
Hmm. So it means I can't make a sub pixi folder like I intended to do. At least not in this project.
Something like this...

![image](https://user-images.githubusercontent.com/883207/30962199-2a0af306-a449-11e7-96a4-32b91459e763.png)

**Comment by whitetigle** [comment]
I have been working through something like this:

```f#
src
|_ pixi
     |_basic
        |_PixiBasic.fsproj
     |_container
        |_PixiContainer.fsproj

public
|_ pixi
     |_basic
        |_index.html
     |_container
        |__index.html
     |_ index.html
     |_ bunny.png

```

But now maybe that's not what we want to do?

**Comment by alfonsogarciacaro** [comment]
Hmm, that probably won't work as it's now but we can modify the scripts for this. If you want to have a single page for Pixi samples (not just a different section as you can see in http://fable.io/samples-browser/) we have two options: 1) modify the script to build the samples-browser; or 2) create a new repo for pixi samples (like we had for fable-graphics in the past).

Actually, my idea was to have different repos like samples-browser, samples-node, samples-electron. Basically samples were the build process was similar so you can share dependencies, build script, etc. Not sure about Pixi, I guess it can go into samples-browser or have an independent repo. Up to you! 😄

**Comment by MangelMaxime** [comment]
If want to have a dedicated page for Pixi, it's probably simpler to create a repo "samples-pixi" indeed. Otherwise, we are going to manage "a lot of special case" inside fable-compiler.github.io repo.

**Comment by whitetigle** [comment]
Well, locally it builds using the following json and after adding each project to the `.sln` file.

```json
  "pixi": {
    "pixi": {
      "entry": "Pixi.fsproj",
      "title": "Pixi official samples",
      "desc": "Fable port of [PixiJS](http://www.pixijs.com/) v4 official samples, a fast and flexible library to render 2D WebGL content.",
      "img": "pixi.jpeg"
    },
    "pixi/basic": {
      "entry": "PixiBasic.fsproj",
      "title": "Pixi sample",
      "desc": "Simple renderization with [PixiJS](http://www.pixijs.com/), a fast and flexible library to render 2D WebGL content.",
      "img": "pixi.jpeg"
    },
    "pixi/container": {
      "entry": "PixiContainer.fsproj",
      "title": "Pixi sample",
      "desc": "Simple renderization with [PixiJS](http://www.pixijs.com/), a fast and flexible library to render 2D WebGL content.",
      "img": "pixi.jpeg"
    },
  },
```
But maybe you are refering to the build process of building the docs through the fable-compiler repo?

**Comment by whitetigle** [comment]
> If want to have a dedicated page for Pixi, it's probably simpler to create a repo "samples-pixi" indeed. Otherwise, we are going to manage "a lot of special case" inside fable-compiler.github.io repo

ok. So do I take the sample repo as the basis for this new project or should I move to any other kind of architecture?

**Comment by MangelMaxime** [comment]
I believe you can take this repo as a the basis. And then push your code to [this repo](https://github.com/fable-compiler/samples-pixi)

Then, we will adapt the [fable-compiler.github.io](https://github.com/fable-compiler/fable-compiler.github.io) repo.

**Comment by whitetigle** [comment]
okidoki gentlemen 👍

**Comment by whitetigle** [comment]
Last question: does it mean the pixi page will be built from the fable-compiler repo or that it will just be a mere link to github pages?

**Comment by alfonsogarciacaro** [comment]
@whitetigle Ideally you should build the page directly in `samples-pixi`. Right now `samples-browser` is a bit messy because the samples are built in that repo but the web page is built in `fable-compiler.github.io`. I need to fix that 😅

**Comment by whitetigle** [comment]
@alfonsogarciacaro Ok! I'll do that then.

**Comment by whitetigle** [comment]
ok first working version pushed: https://github.com/fable-compiler/samples-pixi
