### ISSUE TITLE
Fable.Samples.Browser.sln

### ISSUE THREAD

**Issue by whitetigle** [fable-compiler/samples-browser#11]
Hi!
Is this file required to add a new pixi based project? 
[edit] Do I have to use Visual Studio to add a new project in that file?
Thanks!

**Comment by MangelMaxime** [comment]
This is needed to make restoration quicker.

You can use `dotnet` cli to add your project to this file.
See the [README](https://github.com/fable-compiler/samples-browser#adding-a-new-sample) for more info

**Comment by whitetigle** [comment]
Ahhhhhhhhh. Was deep into my vscode. Did not read the README!

**Repeat to myself 100000 times: RTFM!** 👿 

Sorry guys! 😞
