### ISSUE TITLE
wish there were more samples

### ISSUE THREAD

**Issue by joeaudette** [fable-compiler/samples-browser#14]
Hi,
I am very interested in using F# via fable for client side development. My thinking is that soon there will be tools for writing client side code in better languages than javascript, ie F# and C# and there will eventually be tooling to compile to webassembly. So I think that any effort writing new javascript is really writing legacy code of tomorrow. I watched the video about Fable from dotnetconf and it got me thinking that Fable would be a great way to write client side code with F# today so it gets compiled to js, but eventually there will be tools to compile F# to web assembly and then my F# code would still be of value. So using Fable today would be a good way to make sure I am writing code that will still be useful when javascript goes out of style because my thinking is that everyone will be compiling to web assembly instead of using javascript in a few years.

But the current sample seems like it only uses node for backend web server and I don't want to use node for my backend, I want to use asp.net core. There is webpack middleware for asp.net core which I think/hope would allow using fable in asp.net core similar to how it is used in node. All the [asp.net core spa templates](https://blogs.msdn.microsoft.com/webdev/2017/02/14/building-single-page-applications-on-asp-net-core-with-javascriptservices/) use it, namespace is Microsoft.AspNetCore.SpaServices.Webpack

So my wish is for a sample that uses asp.net core web api as the backend with use of F# for client side code, and server side code could be in either F# or C#.  So that would be like a spa sample for asp.net core with fable.

I would also love to use it in MVC projects even though there is much less use of client side code I still would like to write all my client side code in F#, so I would also love to see an asp.net core mvc app sample setup to write client side code in F#.

I have spent a few hours trying to figure out how to set up a project like the above but I am not expert in webpack or babel as I don't have a background in node development so it has been a losing struggle for me so far.

I know this is a lot to ask and you guys are surely very busy, but it never hurts to ask, and maybe someone with a good background in the various tools involved could help.

**Comment by forki** [comment]
For Server side asp.net you don't really want to use fable but https://github.com/dustinmoris/Giraffe

For a larger sample look at https://github.com/SAFE-Stack/SAFE-BookStore it contains server and client and a lot around. Its not using giraffe but suave on server side. But these are very similar and it's easy to swap.

**Comment by joeaudette** [comment]
@forki thanks for your comment but no that is not what I want. I have no interest at all in giraffe or suave though I am sure they are fine projects and frameworks. I want to use asp.net core. I am primarily a C# developer who is trying to introduce a little F# into my stack, not trying to replace my whole stack with F#. I know giraffe is for asp.net core but I just want to use regular asp.net mvc and web api.

The server side piece for fable is only for during development, ie being able to edit the .fs files and have them automatically re-compiled into js and the browser updated during development like what exists with node in the current sample and which I think could be achieved also in asp.net core using the webpack middleware during development. But I could live with a solution that requires me to run a task when I update .fs files to re-gen the js.

**Comment by forki** [comment]
Giraffe is asp.net core. /shrug


Anyways you can host fable very easily. Just look at the bookstore sample.

Am 30.09.2017 17:07 schrieb "Joe Audette" <notifications@github.com>:

**Comment by forki** [comment]
What I'm trying to say is: look at the bookstore sample. It uses dotnet cli / dotnet core already. It fits perfectly with asp.net core server side. If you use giraffe inside your asp.net core app you get the benefits of "Isomorphic F#" (see bookstore readme). You can even mix C# asp.net core with it or use C# alone

**Comment by joeaudette** [comment]
The bookstore sample does look informative and giraffe also looks interesting but is of secondary interest to my main goal right now.

Possibly I can figure out from the bookstore example how to do what I want. But it is a bit different than what I want. From looking at it briefly it looks like it runs the client using webpack dev server and proxies requests for /api to the different backend server using suave. So maybe I could do that and proxy to a regular asp.net core back end.

But really I would like a more simple model with the same asp.net core api project serving both the client side files ie index.html or perhaps even using a razor view index.cshtml with a controller. The part I want to do away with is the separate webpack dev server if that is possible but maybe that is the only way the fable daemon can run? If it could be run using the webpack middleware for asp.net core then my client code and server code could all be in the single web server and the middleware would only be used in dev environment which is what I want

Another alternative that would be good enough for me is if there is a way that I can use fable in a gulp task to process F# into js. Is that possible? Is there a way to run the fable daemon as a separate thing from my app and then process F# into js from a guplfile? Then I could just use the VS task runner to update the js whenever i edit the client side .fs files

**Comment by forki** [comment]
The webpack dev server is only for development. As the name says. If you
build it fully then everything from client is compiled to js and served
from the one real server. In this case this is suave. In your case that
would be asp.net

Am 30.09.2017 18:55 schrieb "Joe Audette" <notifications@github.com>:

**Comment by joeaudette** [comment]
I know that but that is what I don't want to do, I don't want to run a separate web server for the client during development, is that the only possible way? 

Is there any way to use a task to run fable to process F# files into js?
There is gulp-babel so I was thinking maybe there is a way to do it from gulp or does Fable really depend on webpack and must run in webpack dev server?

**Comment by forki** [comment]
No of course it's not the only possible way. But AFAIK the most produv. By
far. Hot Module Replacement makes a hell of a difference.

Am 30.09.2017 19:25 schrieb "Joe Audette" <notifications@github.com>:

**Comment by joeaudette** [comment]
hot module replacement is what the webpack middleware for asp.net core is for and elminates the need for a separate web server for client side and if I could get it working that would be great but I guess I need to learn a lot more about webpack syntax to figure out how to set it up. That is why i wish there was already a sample like that, I struggled with it some hours already without success.

I have a little more familiarity with gulp so maybe I should try that approach for now, but it is unclear to me how that would work, could I launch the fable daemon standalone somehow and then pass files to it from gulp-babel? I wish there was an example for that too.

**Comment by forki** [comment]
I seriously think you should stop for a moment and evaluate the things that
we already have in depth.

Am 30.09.2017 19:41 schrieb "Joe Audette" <notifications@github.com>:

**Comment by 7sharp9** [comment]
I think looking at the samples that already exist give you a really good idea of what you can do.  Further examples can be created but these of course take a bit of time.

With regards to web pack errors, web pack does take a while to set up but once thats done it tends to run quite well.  Im sure if you got a sample repo up and running people would be able to advise on how things may need to be tweaked to get it running.

**Comment by joeaudette** [comment]
I'll be the first to admit I have a lot to learn, but more samples would lower the barrier of entry. 

I will try to get back to this soon and setup a repo, I think you are right that would make it easier for people to help me, if they can see what I've done and where I am stuck.  That is a very good idea. I will follow up again after I do that.

**Comment by forki** [comment]
Also go and ask on fable gitter Chat. There are many helpful people. Maybe some does something similar.

**Comment by alfonsogarciacaro** [comment]
@joeaudette Thanks for your kind words, you're right in that we're a small team so it's difficult to provide samples and documentation for all use cases, so any help from the community is really appreciated!

If you haven't already please have a look at [the section in the documentation that explains how Fable works](http://fable.io/docs/getting-started.html#a-bit-longer-explanation). In fact Fable daemon is a stand-alone .NET TCP server that works independently of the so-called Fable JS clients, which interact with both the daemon and Babel to generate the actual JS code. As @forki says, the Webpack development server is just a convenience for development but it's not required at all by Fable, you can just use Webpack (or any other of the [Fable JS clients](http://fable.io/docs/getting-started.html#a-bit-longer-explanation)) if you already have a working server. I don't know how ASP.NET Core middleware works, but if you can run Webpack through it I'm pretty sure you should be able to use the [fable-loader](https://www.npmjs.com/package/fable-loader) with the same syntax.

About gulp, I haven't used it so unfortunately I cannot write a Fable task for it, but if you need it and could contribute it to the community, it'd be great! You can have a look at [fable-splitter source code](https://github.com/fable-compiler/Fable/tree/master/src/js/fable-splitter) and see how the interaction with Fable daemon is done. BTW, if you just need a process that compiles (and watches) F# files into JS without further ceremony (no bundling, etc), [fable-splitter](https://www.npmjs.com/package/fable-splitter) may be what you're looking for.

Please also note that Fable is independent of the server technology, so you can use Suave, Giraffe, ASP.NET Core Web API or MVC (or a non-F# server for that matter). The main advantage of using F# on the server is you can use the [`Fable.JsonConverter` to share the domain model between your app back and front ends](http://fable.io/docs/interacting.html#json-serialization).

**Comment by joeaudette** [comment]
Thanks @alfonsogarciacaro  and also thanks @forki for your help. If I can get a sample working the way I want it to work I am happy to share it back.

I have started an effort to setup the solution model I would like and trying to get it working. I have made some progress using webpack.config.js based on safe-stack bookstore sample but also with some modifications based on another sample that uses the asp.net core webpack middleware. You can see my work so far here:

https://github.com/joeaudette/fable-samples/tree/master/SpaApp

and maybe give me advice.

One thing is I am using C# for the main webapp/console app and keeping the F# client side code in a separate class library project. So I'm trying to make it load the .fsproj and .fs  files from a folder up from the main webapp/console app

I am trying to use the same asp.net core web app to serve both the client side static files and the server side api.

I am also trying to use the webpack middleware for asp.net core to do the hot module reloading. 

So far my client side index.html is only trying to load the same .fs file as the current sample and bundling it as wwwroot/dist/bundle.js, and my index.html has the same markup as the current sample and not talking to the api yet, just trying to get the .fs to .js working

I'm using the asp.net core static files middleware to serve the index.html file out of the wwwroot folder

I'm done working for today but will give it another try tomorrow. At this point it seems like the middleware is working and trying to contact fable but I haven't got fable daemon running. The error I see in chrome console is:

Uncaught Error: Module build failed: Error: connect ECONNREFUSED 127.0.0.1:61225
Make sure Fable server is running on port 61225
    at Loader.fableUtils.client.send.then.catch.err (c:\_c\fable-samples\SpaApp\SpaApp\node_modules\fable-loader\index.js:110:18)
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at Loader.fableUtils.client.send.then.catch.err (c:\_c\fable-samples\SpaApp\SpaApp\node_modules\fable-loader\index.js:110:18)
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at Object.../fab/fab.fsproj (http://localhost:5000/dist/bundle.js:1392:7)
    at __webpack_require__ (http://localhost:5000/dist/bundle.js:1335:30)
    at fn (http://localhost:5000/dist/bundle.js:742:20)
    at Object.0 (http://localhost:5000/dist/bundle.js:2865:18)
    at __webpack_require__ (http://localhost:5000/dist/bundle.js:1335:30)
    at ../fab/fab.fsproj (http://localhost:5000/dist/bundle.js:1384:37)
    at http://localhost:5000/dist/bundle.js:1387:10
:5000/wwwroot/dist__webpack_hmr Failed to load resource: the server responded with a status of 404 (Not Found)
:5000/favicon.ico Failed to load resource: the server responded with a status of 404 (Not Found)

I try to run the command:

    dotnet fable start

and I get: No executable found matching command "dotnet-fable"

so I think I am misunderstanding something basic on how to setup fable and launch it. I have installed the template for the dotnet cli but maybe it didn't update my path or something. I will try again tomorrow with fresh coffee.

**Comment by joeaudette** [comment]
I also do want to use some F# code on the server, but I want to do that in class libraries and keep the main web console app as c# at least for the sample I am trying to create right now. Using the Fable.JsonConverter to share code between the server and client is appealing but I think I can still do that since most of my code is always in class library projects. The main web console app for my thinking is just the composition root where everything gets wired up by DI, most of my code goes into other library projects and I am working with a lot of C# libraries but want to be able to write some things in F# on the server as well but being pragmatic not to throw out a lot of good working C# code I already have so I'm not trying to go pure on F# and functional patterns on the server at this point. But I do want to start things moving in the functional direction wherever I can and client side seems like a good place to start.

**Comment by joeaudette** [comment]
@alfonsogarciacaro @forki good news! I got this sample working, it is drawing the squares on the canvas like in your sample.

I finally got the fable daemon running. I was getting an error about paket when doing dotnet restore, the error was about packet.lock file missing which I thought was supposed to be generated. I copied it from your sample and then dotnet restore worked and restored the packet dependencies and then I was able to do dotnet fable start.

https://github.com/joeaudette/fable-samples/tree/master/SpaApp

but I am seeing this error in chrome dev tools:

failed to load resource: the server responded with a status of 404 (Not Found) :5000/wwwroot/dist__webpack_hmr 

Any ideas what that is about or how to solve it?
Note that I am bundling into wwwroot/dist/bundle.js so it seems related but there is no such file "dist__webpack_hmr" in my wwwroot folder

**Comment by forki** [comment]
Better nuke the lock file again and call Pakete install to generate the
lock file properly.

Am 01.10.2017 13:39 schrieb "Joe Audette" <notifications@github.com>:

**Comment by joeaudette** [comment]
@forki thanks, that worked, I'm new to paket

any ideas about the 404 for "dist__webpack_hmr"?

**Comment by forki** [comment]
No sorry.

Am 01.10.2017 14:20 schrieb "Joe Audette" <notifications@github.com>:

**Comment by joeaudette** [comment]
solved it, the problem was in my webpack.config.js I had this:

    publicPath: "/wwwroot/dist",

but it needed a trailing slash:

    publicPath: "/wwwroot/dist/",

the request for dist__webpack_hmr really needed to be dist/__webpack_hmr that is why it was a 404

**Comment by forki** [comment]
We would be happy to see your work as new sample. And btw: welcome to the
fable community. How can we help you to publish the sample?

Am 01.10.2017 18:24 schrieb "Joe Audette" <notifications@github.com>:

**Comment by joeaudette** [comment]
Thanks for the welcome and thanks for your help!

I would be happy to share it however you would like. I was thinking about making some improvements to it and then publishing as a dotnet new template.

There are still a few things I want to figure out such as how to make the webpack setup handle more than one entry, so I can set it up to also process scss/css. Right now the F# code is in a separate class library project than the main web but I would like to be able to process css from within the main web app. Also I'm not sure yet how to do it if my .fs files depend on some js where should I put the js files in the main app or in the F# project.

Another question I have is whether it is possible to group things into separate bundles or process more than one set of F# files into different bundles. I think for spa style apps it is ok to put everything in one bundle but I would also like to be able to use F# for client code in asp.net mvc style apps where different pages in the app might need different bundles.

**Comment by joeaudette** [comment]
I could also easily make an example with F# for the asp.net core server side code
