### ISSUE TITLE
Pixi samples.

### ISSUE THREAD

**Issue by whitetigle** [fable-compiler/samples-browser#9]
Howdy!

The first draft of the new bindings for pixi.js v4.5.5 are currently under development.
I have to go through **all the samples** again to check the new API.
So since all this code is going to exist somewhere, I wonder if we could not add it to this repo under some pixi sub category (like vizualisation).

What do you think?

**Comment by alfonsogarciacaro** [comment]
I think it's a great idea! This way they'll be uploaded to the web automatically :+1:

**Comment by whitetigle** [comment]
ok! I'll do that 👍
